import { spawnSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const PUBLIC_DIR = new URL("../public/", import.meta.url);
const RUNTIME_CONFIG_PATH = new URL("runtime-config.js", PUBLIC_DIR);

const update = spawnSync(process.execPath, [fileURLToPath(new URL("update-schedule.mjs", import.meta.url))], {
  stdio: "inherit",
  env: process.env
});

if (update.status !== 0) {
  process.exit(update.status ?? 1);
}

const workerBaseUrl = normalizeBaseUrl(process.env.PUBLIC_WORKER_BASE_URL);
const runtimeConfig = [
  "// Generated by scripts/build-site.mjs during deployment.",
  `window.FIFA_WORKER_BASE_URL = ${JSON.stringify(workerBaseUrl)};`,
  ""
].join("\n");

writeFileSync(RUNTIME_CONFIG_PATH, runtimeConfig);
console.log(`Configured Worker base URL: ${workerBaseUrl || "(static files)"}`);

function normalizeBaseUrl(value) {
  if (typeof value !== "string" || !value.trim()) return "";
  return value.trim().replace(/\/+$/, "");
}
